import type { Metadata } from "next";
import "../app/globals.css";

export const metadata: Metadata = {
  title: "BLOCK BEATS ⛓️⛓️",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`bg-black antialiased`}>{children}</body>
    </html>
  );
}
