#import "lyrics_data.typ" : title, subtitle, date, artist, verses, footnotes

// Page setup
#set page(
  paper: "a4",
  margin: (x: 1.5cm, y: 1.2cm),  // Reduced margins to fit more content
  fill: rgb("#fffef0"),
  header: [
    #set text(size: 8pt, style: "italic", fill: rgb("#666666"))
    #align(right)[#artist · #date]
    #line(length: 100%, stroke: 0.5pt + rgb("#cccccc"))
  ],
  footer: [
    #line(length: 100%, stroke: 0.5pt + rgb("#cccccc"))
    #grid(
      columns: (1fr, 1fr),
      gutter: 0pt,
      [#set text(size: 8pt, fill: rgb("#666666"), style: "italic")
       #align(left)[Multibase]],
      [#set text(size: 8pt, fill: rgb("#666666"), style: "italic")
       #align(right)[February 2025]]
    )
  ]
)

// Typography
#set text(font: "New Computer Modern", fill: rgb("#333333"), size: 9.5pt)
#set par(justify: false, leading: 0.65em)

// Verse styling function
#let style-verse(verse) = {
  let type = verse.type
  
  // Different styling for different verse types
  if type == "verse" {
    [
      // Section title with left alignment and compact styling
      #text(weight: "bold", style: "italic", size: 10pt, fill: rgb("#5a3d2b"))[
        Verse #verse.number:
      ]
      
      // No vertical space after title - more compact
      
      // Content with better styling and reduced indentation
      #block(
        width: 100%,
        inset: (left: 0.3cm, right: 0.2cm, top: 0.1cm, bottom: 0.1cm),
        verse.content
      )
    ]
  } else if type == "chorus" {
    [
      // Section title with left alignment and compact styling
      #text(weight: "bold", style: "italic", size: 10pt, fill: rgb("#5a3d2b"))[
        Chorus:
      ]
      
      // No vertical space after title - more compact
      
      // Content with better styling and reduced indentation - no background
      #block(
        width: 100%,
        inset: (left: 0.3cm, right: 0.2cm, top: 0.1cm, bottom: 0.1cm),
        verse.content
      )
    ]
  } else if type == "bridge" {
    [
      // Section title with left alignment and compact styling
      #text(weight: "bold", style: "italic", size: 10pt, fill: rgb("#5a3d2b"))[
        Bridge:
      ]
      
      // No vertical space after title - more compact
      
      // Content with better styling and reduced indentation
      #block(
        width: 100%,
        inset: (left: 0.3cm, right: 0.2cm, top: 0.1cm, bottom: 0.1cm),
        verse.content
      )
    ]
  } else if type == "outro" {
    [
      // Section title with left alignment and compact styling
      #text(weight: "bold", style: "italic", size: 10pt, fill: rgb("#5a3d2b"))[
        Outro:
      ]
      
      // No vertical space after title - more compact
      
      // Content with better styling and reduced indentation
      #block(
        width: 100%,
        inset: (left: 0.3cm, right: 0.2cm, top: 0.1cm, bottom: 0.1cm),
        verse.content
      )
    ]
  }
}

// Title section
#align(center)[
  #block(
    width: 100%,
    inset: 6pt,
    {
      align(center)[
        #text(size: 20pt, weight: "bold", fill: rgb("#48301a"))[#title]
        #if subtitle != "" [
          #v(0.2cm)
          #text(size: 12pt, style: "italic", fill: rgb("#666666"))[#subtitle]
        ]
      ]
    }
  )
]

#v(0.2cm)

// Lyrics
#for verse in verses [
  #style-verse(verse)
  #v(0.4cm)  // Reduced spacing between sections
]


// Credits - more compact
#align(right)[
  #text(style: "italic", size: 7pt)[
    Generated by Multibase · #date · #artist
  ]
]